# Labeler configuration for auto-labeling PRs based on file changes

# Frontend/UI changes
ui:
  - changed-files:
    - any-glob-to-any-file: 'src/components/**/*'
  - changed-files:
    - any-glob-to-any-file: 'src/pages/**/*'
  - changed-files:
    - any-glob-to-any-file: '**/*.css'
  - changed-files:
    - any-glob-to-any-file: '**/*.scss'

# API/Services changes  
api:
  - changed-files:
    - any-glob-to-any-file: 'src/services/**/*'
  - changed-files:
    - any-glob-to-any-file: 'src/hooks/**/*'

# Configuration changes
config:
  - changed-files:
    - any-glob-to-any-file: '*.json'
  - changed-files:
    - any-glob-to-any-file: '*.js'
  - changed-files:
    - any-glob-to-any-file: '*.ts'
  - changed-files:
    - any-glob-to-any-file: '.env*'
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'
  - changed-files:
    - any-glob-to-any-file: 'vite.config.*'
  - changed-files:
    - any-glob-to-any-file: 'tsconfig.*'

# Documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
  - changed-files:
    - any-glob-to-any-file: 'docs/**/*'

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file: 'package.json'
  - changed-files:
    - any-glob-to-any-file: 'package-lock.json'

# Testing
testing:
  - changed-files:
    - any-glob-to-any-file: '**/*.test.*'
  - changed-files:
    - any-glob-to-any-file: '**/*.spec.*'
  - changed-files:
    - any-glob-to-any-file: 'test/**/*'
  - changed-files:
    - any-glob-to-any-file: '__tests__/**/*'

# TypeScript types
types:
  - changed-files:
    - any-glob-to-any-file: 'src/types/**/*'
  - changed-files:
    - any-glob-to-any-file: '**/*.d.ts'

# Build/CI
build:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**/*'
  - changed-files:
    - any-glob-to-any-file: 'vite.config.*'
  - changed-files:
    - any-glob-to-any-file: 'Dockerfile*'