apiVersion: v1
kind: ConfigMap
metadata:
  name: ssvirt-nginx-config
  labels:
    app: ssvirt-ui
    component: nginx-proxy
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream ui_backend {
            server localhost:8080;
        }
        
        upstream api_backend {
            server ssvirt-backend.ssvirt.svc.cluster.local:8080;
        }
        
        server {
            listen 8081;
            
            # Serve UI application
            location / {
                proxy_pass http://ui_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            # Proxy API requests to backend
            location /api/ {
                proxy_pass http://api_backend/api/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }